### ISSUE TITLE
Option to disable album art?

### ISSUE THREAD

**Issue by sxdjt** [mcthomas/Apple-Music-CLI-Player#2]
First off, thank you for this!  Nice to be able to have a CLI interface without the Music app in your face.

Is there a way to completely disable album art display?  I would like to have the np output by itself and not have a big black square on the left side of the output.

**Comment by mcthomas** [comment]
That's a good idea, I hadn't accommodated this.  I will push a new flag tomorrow (later today) to start np without album art.

**Comment by sxdjt** [comment]
Cool, thank you!  I tried doing it myself and just ended up breaking things miserably.

**Comment by sxdjt** [comment]
An option to disable the icons would be nice as well, while you have the lid off?

**Comment by mcthomas** [comment]
I just pushed an update to hide the album art behind the `-t` flag.  I don't see the value in disabling the emojis, since this new flag already operates as a text only mode.  I think I am going to leave it at that for now.  That being said, after you pull down, you are welcome to just replace line #93 with the following to remove the icons when you call `am np -t`:
```
paste <(printf '%s\n' "$name" "$artist - $record" "$(echo $currMin:$currSec ${cyan}${prog}${nocolor}${progBG} $endMin:$endSec)" "$(echo "${magenta}$vol${nocolor}$volBG")")
```

**Comment by sxdjt** [comment]
*Nice!*  Thank you!

**Comment by mcthomas** [comment]
@sxdjt by the way, did you see the dependency listing for [viu](https://github.com/atanunq/viu) on the readme?  I just wanted to make sure you knew that you would have proper album art in place of that whitespace if you have that package installed.

**Comment by sxdjt** [comment]
@mcthomas - I did see the dependency and tried it.  Took a bit of fiddling to get it sorted, but in the end wasn't a feature that I would use.  Thank you for the follow up!
