### ISSUE TITLE
pr -T 'illegal option'

### ISSUE THREAD

**Issue by davidem** [mcthomas/Apple-Music-CLI-Player#3]
Hi, thanks for this seemingly cool script, but my first test resulted in an error: 

`➜  ~ am list -p
pr: illegal option -- T
usage: pr [+page] [-col] [-adFfmprt] [-e[ch][gap]] [-h header]
          [-i[ch][gap]] [-l line] [-n[ch][width]] [-o offset]
          [-L locale] [-s[ch]] [-w width] [-] [file ...]`

Tested on macOS 12.6.1, and it appears pr -T is no longer a valid option.

**Comment by davidem** [comment]
ah, -T omits making pages. Perhaps 'column' is easier to use, although you can't specify the amount of columns.

**Comment by mcthomas** [comment]
Hi David,

What was the original command you ran?  `am list -p`?

**Comment by davidem** [comment]
yes, `am list -p`, but fails with every list command, as '-T' is omnipresent 😎

Omitting '-T' from the line gives proper output, but with pages.

**Comment by mcthomas** [comment]
Looks like I had a symlink to a different version of pr, rather than the native package at /usr/bin/pr.  Please pull down and let me know if this is resolved for you, I just pushed a fix.

**Comment by sxdjt** [comment]
`am list -p` works, as do the other lists.  Thank you!

**Comment by davidem** [comment]
Yep, it works! Thanks 👍
