### ISSUE TITLE
Search for artist, album, song, playlist by pattern?

### ISSUE THREAD

**Issue by ajkessel** [mcthomas/Apple-Music-CLI-Player#8]
Would you consider adding the ability to search for content by pattern? This would just require adding a command-line option that would accept a pattern and then grepping that pattern from the osascript output.

For example,
```
am list -a -r '.*Monk.*'
```
would search for every artist with the string "Monk" in it, which would capture "Thelonious Monk," as well as "The Thelonious Monk Quartet," etc.

Maybe easier to just have it be a substring rather than regexp match so `-r 'monk'` would return everything that has "monk" anywhere in it.

**Comment by mcthomas** [comment]
I think I might be confused.  Currently you can fzf for an genre, playlist, artist, album, or song if you don't provide a pattern arg to the program's `play` cmd flags.  Are you saying you'd want that same functionality for the `list` cmd?

**Comment by ajkessel** [comment]
> I think I might be confused. Currently you can fzf for an genre, playlist, artist, album, or song if you don't provide a pattern arg to the program's `play` cmd flags. Are you saying you'd want that same functionality for the `list` cmd?

I think that is what I'm saying -- you can't fzf to see what's available, before picking what you want to play, right?

**Comment by mcthomas** [comment]
Sure you can, just execute:
```
play -s 
play -r 
play -a 
play -p 
play -g
```
And it takes you into fzf.  You can send a kill sig if you want to abort.  The `List` cmd doesn't currently have fzf integrated, because it is really just for dumping out the contents of a collection.  Please let me know if I am totally misunderstanding.

**Comment by ajkessel** [comment]
Oh! I didn't realize that's how those options worked. To be honest, I haven't come across fzf before this. Perhaps you want to tweak the help description if the user doesn't know fzf.

**Comment by mcthomas** [comment]
I tried to make it clear with the usage list-out, indicating the no-arg variants pipe in fzf, but maybe that's not inherently obvious.  Thank you for the suggestion!

**Comment by ajkessel** [comment]
My suggestion is just changing "fzf" to something like "interactive search" to clarify what it is doing.
